import { LoadingContextProvider } from '@/contexts/loadingContext'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Loading } from '@/components/shared'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LoadingContextProvider>
        <body className={inter.className} suppressHydrationWarning={true}>
          <Loading />
          <main>
            {children}
          </main>
        </body>
      </LoadingContextProvider>
    </html>
  )
}
